#!/bin/sh
# Claude Code's native Amazon Bedrock backend and AWS credential chain.
PROVIDER_NAME="bedrock"
PROVIDER_DESC="Anthropic Claude through native Amazon Bedrock integration"

BASE_URL="native://amazon-bedrock"
MODEL="sonnet"
CONTEXT_TOKENS=""

MODEL_OPUS="opus"
MODEL_SONNET="sonnet"
MODEL_HAIKU="haiku"
MODEL_SUBAGENT="sonnet"

EFFORT="max"
AUTH_MODE="native"
NATIVE_BACKEND="bedrock"
EXTRA_ENV="CLAUDE_CODE_USE_BEDROCK=1"
PASSTHROUGH_ENV="CLAUDE_CONFIG_DIR AWS_PROFILE AWS_REGION AWS_DEFAULT_REGION AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN AWS_BEARER_TOKEN_BEDROCK AWS_SHARED_CREDENTIALS_FILE AWS_CONFIG_FILE ANTHROPIC_BEDROCK_BASE_URL ANTHROPIC_BEDROCK_REGION_PREFIX ANTHROPIC_BEDROCK_SERVICE_TIER ANTHROPIC_SMALL_FAST_MODEL_AWS_REGION CLAUDE_CODE_SKIP_AWS_CRED_CACHE CLAUDE_CODE_AWS_CHAIN_RESOLVE_TIMEOUT_MS ANTHROPIC_DEFAULT_OPUS_MODEL ANTHROPIC_DEFAULT_SONNET_MODEL ANTHROPIC_DEFAULT_HAIKU_MODEL CLAUDE_CODE_SUBAGENT_MODEL"

PRE_START=""
POST_STOP=""
HEALTH_CHECK_URL=""
