#!/bin/sh
# Claude Code's native Microsoft Foundry backend and Azure credential chain.
PROVIDER_NAME="foundry"
PROVIDER_DESC="Anthropic Claude through native Microsoft Foundry integration"

BASE_URL="native://microsoft-foundry"
MODEL="sonnet"
CONTEXT_TOKENS=""

MODEL_OPUS="opus"
MODEL_SONNET="sonnet"
MODEL_HAIKU="haiku"
MODEL_SUBAGENT="sonnet"

EFFORT=""
AUTH_MODE="native"
NATIVE_BACKEND="foundry"
EXTRA_ENV="CLAUDE_CODE_USE_FOUNDRY=1"
PASSTHROUGH_ENV="CLAUDE_CONFIG_DIR ANTHROPIC_FOUNDRY_RESOURCE ANTHROPIC_FOUNDRY_BASE_URL ANTHROPIC_FOUNDRY_API_KEY ANTHROPIC_FOUNDRY_AUTH_TOKEN ANTHROPIC_DEFAULT_OPUS_MODEL ANTHROPIC_DEFAULT_SONNET_MODEL ANTHROPIC_DEFAULT_HAIKU_MODEL AZURE_CONFIG_DIR AZURE_TOKEN_CREDENTIALS AZURE_CLIENT_ID AZURE_TENANT_ID AZURE_CLIENT_SECRET AZURE_CLIENT_CERTIFICATE_PATH AZURE_CLIENT_CERTIFICATE_PASSWORD AZURE_CLIENT_SEND_CERTIFICATE_CHAIN AZURE_ADDITIONALLY_ALLOWED_TENANTS AZURE_FEDERATED_TOKEN_FILE IDENTITY_ENDPOINT IDENTITY_HEADER MSI_ENDPOINT MSI_SECRET"

PRE_START=""
POST_STOP=""
HEALTH_CHECK_URL=""
