#!/bin/sh
# Claude Code's native Vertex AI backend and Google ADC credential chain.
PROVIDER_NAME="vertex"
PROVIDER_DESC="Anthropic Claude through native Google Vertex AI integration"

BASE_URL="native://google-vertex-ai"
MODEL="sonnet"
CONTEXT_TOKENS=""

MODEL_OPUS="opus"
MODEL_SONNET="sonnet"
MODEL_HAIKU="haiku"
MODEL_SUBAGENT="sonnet"

EFFORT="max"
AUTH_MODE="native"
NATIVE_BACKEND="vertex"
EXTRA_ENV="CLAUDE_CODE_USE_VERTEX=1"
# Version-specific VERTEX_REGION_CLAUDE_* settings are admitted separately in
# lib/launch.sh after validating their family/version suffix.
PASSTHROUGH_ENV="CLAUDE_CONFIG_DIR ANTHROPIC_VERTEX_PROJECT_ID ANTHROPIC_VERTEX_BASE_URL CLOUD_ML_REGION GOOGLE_APPLICATION_CREDENTIALS GCLOUD_PROJECT GOOGLE_CLOUD_QUOTA_PROJECT ANTHROPIC_DEFAULT_OPUS_MODEL ANTHROPIC_DEFAULT_SONNET_MODEL ANTHROPIC_DEFAULT_HAIKU_MODEL CLAUDE_CODE_SUBAGENT_MODEL"

PRE_START=""
POST_STOP=""
HEALTH_CHECK_URL=""
